[package]
name = "locate-cargo-manifest"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Retrieves the Cargo manifest path by parsing the output of `cargo locate-project`."

[dependencies]
json = "0.11.13"
